[project]
name = "shadowperp"
version = "0.1.0"
description = "Private Perpetual Futures Protocol"

[mxe]
program_id = "5Va2JgK2M2kwkoPdwX4RTjfaqwAXgd5hHSWEP5QS848T"
cluster_offset = 456

[circuits]
path = "encrypted-ixs"

[build]
output = "build"

[devnet]
arcium_program = "Arcj82pX7HxYKLR92qvgZUAd7vGS1k4hQvAFcPATFdEQ"
cluster = "devnet"

[clusters]

[clusters.devnet]
offset = 456
backend = "cerberus"
num_nodes = 2

