[project]
name = "shadowperp"
version = "0.1.0"
description = "Private Perpetual Futures Protocol"

[mxe]
program_id = "11111111111111111111111111111111"
cluster_offset = 0

[circuits]
path = "encrypted-ixs"

[build]
output = "build"

[devnet]
arcium_program = "3R4wZSJFTfCJyofLGrVHPCyjMgP8x2cJCDwKUANKsMAE"
cluster = "devnet"
