import { Program, AnchorProvider, BN, web3 } from "@coral-xyz/anchor";
import {
  PublicKey,
  Connection,
  Transaction,
  TransactionInstruction,
  Keypair,
  SystemProgram,
  SYSVAR_RENT_PUBKEY,
} from "@solana/web3.js";
import {
  TOKEN_PROGRAM_ID,
  getAssociatedTokenAddress,
  createAssociatedTokenAccountInstruction,
} from "@solana/spl-token";
import { x25519 } from "@noble/curves/ed25519";
import { randomBytes } from "crypto";

import {
  ShadowPerpConfig,
  OpenPositionInput,
  EncryptedPosition,
  Market,
  MarginAccount,
  PositionStatus,
  ClosePositionResult,
} from "../types";

// Placeholder for IDL - in production this would be generated by Anchor
const IDL = {} as any;

/**
 * ShadowPerp Client SDK
 *
 * Provides methods for interacting with the ShadowPerp protocol.
 * Handles encryption of position data using Arcium's MPC infrastructure.
 */
export class ShadowPerpClient {
  private program: Program;
  private provider: AnchorProvider;
  private config: ShadowPerpConfig;

  // Encryption state
  private clientPrivateKey: Uint8Array | null = null;
  private clientPublicKey: Uint8Array | null = null;
  private sharedSecret: Uint8Array | null = null;

  constructor(provider: AnchorProvider, config: ShadowPerpConfig) {
    this.provider = provider;
    this.config = config;
    this.program = new Program(IDL, config.programId, provider);
  }

  /**
   * Initialize encryption keys for secure communication with MXE
   */
  async initializeEncryption(): Promise<void> {
    // Generate client keypair for X25519 key exchange
    this.clientPrivateKey = x25519.utils.randomPrivateKey();
    this.clientPublicKey = x25519.getPublicKey(this.clientPrivateKey);

    // Get MXE public key from cluster
    const mxePublicKey = await this.getMXEPublicKey();

    // Derive shared secret
    this.sharedSecret = x25519.getSharedSecret(
      this.clientPrivateKey,
      mxePublicKey
    );

    console.log("Encryption initialized");
  }

  /**
   * Get MXE public key from the cluster account
   */
  private async getMXEPublicKey(): Promise<Uint8Array> {
    // In production, fetch from cluster account
    // For now, return placeholder
    const clusterAccount = await this.provider.connection.getAccountInfo(
      this.config.clusterAddress
    );

    if (!clusterAccount) {
      throw new Error("Cluster account not found");
    }

    // Extract MXE public key from cluster account data
    // The exact offset depends on the Arcium account structure
    return clusterAccount.data.slice(0, 32);
  }

  /**
   * Encrypt a value using the shared secret
   */
  private encrypt(value: BN | number | boolean, nonce: Uint8Array): Uint8Array {
    if (!this.sharedSecret) {
      throw new Error("Encryption not initialized");
    }

    // Convert value to bytes
    let bytes: Uint8Array;
    if (typeof value === "boolean") {
      bytes = new Uint8Array([value ? 1 : 0]);
    } else if (typeof value === "number") {
      bytes = new Uint8Array(8);
      new DataView(bytes.buffer).setBigUint64(0, BigInt(value), true);
    } else {
      bytes = value.toArrayLike(Buffer, "le", 8);
    }

    // In production, use RescueCipher from @arcium-hq/client
    // For now, return XOR with shared secret (placeholder)
    const encrypted = new Uint8Array(32);
    for (let i = 0; i < bytes.length; i++) {
      encrypted[i] = bytes[i] ^ this.sharedSecret[i % 32];
    }
    for (let i = bytes.length; i < 32; i++) {
      encrypted[i] = nonce[i % 16] ^ this.sharedSecret[i % 32];
    }

    return encrypted;
  }

  // ============ MARKET OPERATIONS ============

  /**
   * Get market account address
   */
  getMarketAddress(collateralMint: PublicKey): PublicKey {
    const [marketPda] = PublicKey.findProgramAddressSync(
      [Buffer.from("market"), collateralMint.toBuffer()],
      this.config.programId
    );
    return marketPda;
  }

  /**
   * Fetch market state
   */
  async getMarket(marketAddress: PublicKey): Promise<Market> {
    const account = await this.program.account.market.fetch(marketAddress);
    return account as unknown as Market;
  }

  // ============ MARGIN ACCOUNT OPERATIONS ============

  /**
   * Get margin account address
   */
  getMarginAccountAddress(market: PublicKey, owner: PublicKey): PublicKey {
    const [marginPda] = PublicKey.findProgramAddressSync(
      [Buffer.from("margin"), market.toBuffer(), owner.toBuffer()],
      this.config.programId
    );
    return marginPda;
  }

  /**
   * Fetch margin account state
   */
  async getMarginAccount(marginAddress: PublicKey): Promise<MarginAccount> {
    const account = await this.program.account.marginAccount.fetch(
      marginAddress
    );
    return account as unknown as MarginAccount;
  }

  /**
   * Deposit collateral to margin account
   */
  async depositCollateral(
    market: PublicKey,
    amount: BN
  ): Promise<string> {
    const owner = this.provider.wallet.publicKey;
    const marketAccount = await this.getMarket(market);

    const marginAccount = this.getMarginAccountAddress(market, owner);
    const userTokenAccount = await getAssociatedTokenAddress(
      marketAccount.collateralMint,
      owner
    );

    const [vault] = PublicKey.findProgramAddressSync(
      [Buffer.from("vault"), market.toBuffer()],
      this.config.programId
    );

    const tx = await this.program.methods
      .depositCollateral(amount)
      .accounts({
        owner,
        market,
        marginAccount,
        userTokenAccount,
        vault,
        tokenProgram: TOKEN_PROGRAM_ID,
        systemProgram: SystemProgram.programId,
      })
      .rpc();

    console.log("Deposited collateral:", amount.toString());
    return tx;
  }

  /**
   * Withdraw collateral from margin account
   */
  async withdrawCollateral(
    market: PublicKey,
    amount: BN
  ): Promise<string> {
    const owner = this.provider.wallet.publicKey;
    const marketAccount = await this.getMarket(market);

    const marginAccount = this.getMarginAccountAddress(market, owner);
    const userTokenAccount = await getAssociatedTokenAddress(
      marketAccount.collateralMint,
      owner
    );

    const [vault] = PublicKey.findProgramAddressSync(
      [Buffer.from("vault"), market.toBuffer()],
      this.config.programId
    );

    const tx = await this.program.methods
      .withdrawCollateral(amount)
      .accounts({
        owner,
        market,
        marginAccount,
        userTokenAccount,
        vault,
        tokenProgram: TOKEN_PROGRAM_ID,
      })
      .rpc();

    console.log("Withdrew collateral:", amount.toString());
    return tx;
  }

  // ============ POSITION OPERATIONS ============

  /**
   * Get position account address
   */
  getPositionAddress(
    market: PublicKey,
    owner: PublicKey,
    index: BN
  ): PublicKey {
    const [positionPda] = PublicKey.findProgramAddressSync(
      [
        Buffer.from("position"),
        market.toBuffer(),
        owner.toBuffer(),
        index.toArrayLike(Buffer, "le", 8),
      ],
      this.config.programId
    );
    return positionPda;
  }

  /**
   * Open a new encrypted position
   *
   * Position details (size, leverage, direction) are encrypted using MPC.
   * Only the margin amount is visible on-chain.
   */
  async openPosition(
    market: PublicKey,
    input: OpenPositionInput
  ): Promise<{ txSignature: string; positionAddress: PublicKey }> {
    if (!this.clientPublicKey) {
      await this.initializeEncryption();
    }

    const owner = this.provider.wallet.publicKey;
    const marketAccount = await this.getMarket(market);
    const marginAccount = this.getMarginAccountAddress(market, owner);

    // Generate nonce for this encryption
    const nonce = randomBytes(16);

    // Encrypt position parameters
    const encryptedSize = this.encrypt(input.size, nonce);
    const encryptedEntryPrice = this.encrypt(input.entryPrice, nonce);
    const encryptedLeverage = this.encrypt(input.leverage, nonce);
    const encryptedIsLong = this.encrypt(input.direction === "long", nonce);

    // Generate computation offset for tracking
    const computationOffset = new BN(randomBytes(8));

    // Get position address (using current active positions count as index)
    const positionAddress = this.getPositionAddress(
      market,
      owner,
      marketAccount.activePositions
    );

    // Build Arcium computation accounts (placeholders)
    const computation = Keypair.generate().publicKey;
    const cluster = this.config.clusterAddress;
    const mxe = marketAccount.mxeCluster;
    const mempool = Keypair.generate().publicKey;
    const executingPool = Keypair.generate().publicKey;
    const compDef = marketAccount.openPositionCompDef;

    const tx = await this.program.methods
      .openPosition(
        Array.from(encryptedSize),
        Array.from(encryptedEntryPrice),
        Array.from(encryptedLeverage),
        Array.from(encryptedIsLong),
        Array.from(this.clientPublicKey!),
        Array.from(nonce),
        computationOffset
      )
      .accounts({
        owner,
        market,
        marginAccount,
        position: positionAddress,
        computation,
        cluster,
        mxe,
        mempool,
        executingPool,
        compDef,
        arciumProgram: this.config.mxeProgramId,
        systemProgram: SystemProgram.programId,
      })
      .rpc();

    console.log("Position opening queued");
    console.log("Position address:", positionAddress.toBase58());
    console.log("Computation offset:", computationOffset.toString());

    return { txSignature: tx, positionAddress };
  }

  /**
   * Close an existing position
   *
   * Triggers MPC computation to calculate and reveal the final PnL.
   */
  async closePosition(
    market: PublicKey,
    positionIndex: BN
  ): Promise<string> {
    const owner = this.provider.wallet.publicKey;
    const marketAccount = await this.getMarket(market);
    const positionAddress = this.getPositionAddress(market, owner, positionIndex);

    const computationOffset = new BN(randomBytes(8));

    // Build Arcium computation accounts (placeholders)
    const computation = Keypair.generate().publicKey;
    const cluster = this.config.clusterAddress;
    const mxe = marketAccount.mxeCluster;
    const mempool = Keypair.generate().publicKey;
    const executingPool = Keypair.generate().publicKey;
    const compDef = marketAccount.closePositionCompDef;

    const tx = await this.program.methods
      .closePosition(computationOffset)
      .accounts({
        owner,
        market,
        position: positionAddress,
        computation,
        cluster,
        mxe,
        mempool,
        executingPool,
        compDef,
        arciumProgram: this.config.mxeProgramId,
        systemProgram: SystemProgram.programId,
      })
      .rpc();

    console.log("Position close queued");
    console.log("Computation offset:", computationOffset.toString());

    return tx;
  }

  /**
   * Fetch position state
   */
  async getPosition(positionAddress: PublicKey): Promise<EncryptedPosition> {
    const account = await this.program.account.position.fetch(positionAddress);
    return account as unknown as EncryptedPosition;
  }

  /**
   * Get all positions for a user
   */
  async getUserPositions(
    market: PublicKey,
    owner: PublicKey
  ): Promise<EncryptedPosition[]> {
    const accounts = await this.program.account.position.all([
      {
        memcmp: {
          offset: 8, // After discriminator
          bytes: owner.toBase58(),
        },
      },
      {
        memcmp: {
          offset: 8 + 32, // After owner
          bytes: market.toBase58(),
        },
      },
    ]);

    return accounts.map((a) => a.account as unknown as EncryptedPosition);
  }

  // ============ LIQUIDATION ============

  /**
   * Check if a position can be liquidated
   *
   * This triggers an MPC computation that returns only a boolean result.
   * The actual health factor is NEVER revealed.
   */
  async checkLiquidation(
    market: PublicKey,
    positionOwner: PublicKey,
    positionIndex: BN
  ): Promise<string> {
    const marketAccount = await this.getMarket(market);
    const positionAddress = this.getPositionAddress(
      market,
      positionOwner,
      positionIndex
    );

    const computationOffset = new BN(randomBytes(8));

    // Build Arcium computation accounts
    const computation = Keypair.generate().publicKey;
    const cluster = this.config.clusterAddress;
    const mxe = marketAccount.mxeCluster;
    const mempool = Keypair.generate().publicKey;
    const executingPool = Keypair.generate().publicKey;
    const compDef = marketAccount.liquidationCompDef;

    const tx = await this.program.methods
      .checkLiquidation(marketAccount.oraclePrice, computationOffset)
      .accounts({
        liquidator: this.provider.wallet.publicKey,
        market,
        position: positionAddress,
        computation,
        cluster,
        mxe,
        mempool,
        executingPool,
        compDef,
        arciumProgram: this.config.mxeProgramId,
        systemProgram: SystemProgram.programId,
      })
      .rpc();

    console.log("Liquidation check queued");
    console.log("Mark price:", marketAccount.oraclePrice.toString());

    return tx;
  }

  // ============ EVENTS ============

  /**
   * Subscribe to position events
   */
  onPositionOpened(
    callback: (event: any, slot: number) => void
  ): number {
    return this.program.addEventListener("PositionOpened", callback);
  }

  onPositionClosed(
    callback: (event: any, slot: number) => void
  ): number {
    return this.program.addEventListener("PositionClosed", callback);
  }

  onPositionLiquidated(
    callback: (event: any, slot: number) => void
  ): number {
    return this.program.addEventListener("PositionLiquidated", callback);
  }

  /**
   * Remove event listener
   */
  async removeEventListener(listenerId: number): Promise<void> {
    await this.program.removeEventListener(listenerId);
  }
}
