[package]
name = "shadowperp"
version = "0.1.0"
description = "ShadowPerp - Private Perpetual Futures on Arcium"
edition = "2021"

[package.metadata.solana]
tools-version = "v1.53"

[lib]
crate-type = ["cdylib", "lib"]
name = "shadowperp"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
idl-build = ["anchor-lang/idl-build", "anchor-spl/idl-build", "arcium-anchor/idl-build", "shielded-collateral"]
shielded-collateral = []
default = []

[dependencies]
anchor-lang = { version = "=0.32.1", features = ["init-if-needed"] }
anchor-spl = "=0.32.1"
arcium-anchor = "=0.9.3"
arcium-client = { version = "=0.9.3", default-features = false }
arcium-macros = "=0.9.3"
bytemuck = { version = "1.14", features = ["derive"] }
sha2 = "0.10"
pyth-solana-receiver-sdk = "=1.1.0"
solana-instruction = "=2.3.3"
